### ISSUE TITLE
API

### ISSUE THREAD

**Issue by SamIsOnMC** [tavonkelly/BungeeServerManager#10]
Ight, how do i use the API? I am currently trying to make an [PlayerServers](https://www.spigotmc.org/wiki/bbcode.2858/archive) alternative, because player servers got taken offline from spigot.

**Comment by tavonkelly** [comment]
Get an instance of the `ServerManagerAPI` class by calling `BungeeServerManager#getApi()`. So something like:
```java
ServerManagerAPI serverManagerAPI = BungeeServerManager.getApi();
```

You'll have access to the following methods inside [`ServerManagerAPI`](https://github.com/tavonkelly/BungeeServerManager/blob/507b67df7e1c18c337bf6b540a42485c33e5100b/src/main/java/pw/teg/bsm/api/ServerManagerAPI.java):
```java
boolean addServer(String name, InetSocketAddress ipAddress, String motd, boolean restricted);
boolean removeServer(String name);
boolean serverExists(String name);
Collection<ServerInfo> listServers();
```

There's also the following events you can listen to (from the [events package](https://github.com/tavonkelly/BungeeServerManager/tree/1108b2d76a4b0dc7592da7524240d9b7cd508cf2/src/main/java/pw/teg/bsm/api/events)):
```
ServerAddEvent
ServerModifiedEvent
ServerRemoveEvent
```
These events are only fired when someone uses the plugin's commands and they are all cancellable.
