### ISSUE TITLE
Add hostnames support

### ISSUE THREAD

**Issue by ghost** [tavonkelly/BungeeServerManager#2]

**Comment by TiTo-418** [comment]
I'm stupid

**Comment by TiTo-418** [comment]
Actually, it would be cool

**Comment by tavonkelly** [comment]
Elaborate?

**Comment by TiTo-418** [comment]
@tavonkelly Be able to add a server with the ip "example.com"

**Comment by tavonkelly** [comment]
Added in https://github.com/tavonkelly/BungeeServerManager/commit/a52f7a2939c0bb371d996078e65f5fd2bbab6d21. Sorry it took so long
