### ISSUE TITLE
Wrong command image

### ISSUE THREAD

**Issue by KasperFranz** [tavonkelly/BungeeServerManager#3]
The provided command image in the readme (and on the spigot forum) is refering to a uptime plugin :)?

**Comment by tavonkelly** [comment]
Oh wow I didn't notice that. Should be fixed now

**Comment by KasperFranz** [comment]
It seems to still be a wrong one

**Comment by tavonkelly** [comment]
I'm pretty sure it's the right one. Clear your cache and check again
