### ISSUE TITLE
error

### ISSUE THREAD

**Issue by oliverjdk** [tavonkelly/BungeeServerManager#5]
can't add a server I get kicked and get the message

the command I use: /svm add end 144.76.17.56:27000

NoSuchMethodError : net.md_5.bungee.bungeeserverinfo.<init>(Ljava/lang/String:Ljava/net/InetSocketAddress;Ljava/lang/String;Z)V @ pw.teg.bsm.commands.ServerManagerCommand:163

**Comment by tavonkelly** [comment]
Should be fixed in latest commit b7ef6709da4dba6c79a4f4e6968ec2c568b518ee
