### ISSUE TITLE
"serverList" support for API

### ISSUE THREAD

**Issue by tyuop077** [tavonkelly/BungeeServerManager#6]
Is it possible to add "serverList" support? /svm list already shows server list, but parsing command's result isn't best idea for me. Thank you!
[ServerManagerAPI](https://github.com/tavonkelly/BungeeServerManager/blob/master/src/main/java/pw/teg/bsm/api/ServerManagerAPI.java)

**Comment by tavonkelly** [comment]
Added in https://github.com/tavonkelly/BungeeServerManager/commit/8fd1fc702d61d8840024ad523983d4e1c882de0b. Sorry for the long wait
