### ISSUE TITLE
Forced Host Support?

### ISSUE THREAD

**Issue by Artucuno** [tavonkelly/BungeeServerManager#9]
Hey I was wondering if you could add Forced Host support? This would really help me out.

Thanks!

**Comment by Articuno1234** [comment]
Hey just wondering if you guys got my issue.
I don't think I explained it well enough anyway lol

I meant add domain support for servers so you could do `/svm edit <name> domain server.example.com' so people can connect via that domain
```
  forced_hosts:
    server.example.com: testserver
```

**Comment by tavonkelly** [comment]
Ahh I see. I'll work on adding something like that

**Comment by Articuno1234** [comment]
Thankyou!

**Comment by BasToTheMax** [comment]
> Ahh I see. I'll work on adding something like that

What is the status of this?

**Comment by tavonkelly** [comment]
Added the feature in e6b756fd5e0cc6272d9a7af2a458cc831ae58635.

**Comment by BasToTheMax** [comment]
Will you publish a new release to the spigot page?

**Comment by tavonkelly** [comment]
Just published https://www.spigotmc.org/resources/bungeeservermanager.7388/update?update=456902

**Comment by BasToTheMax** [comment]
Thx!
